# Generated by Django 2.2.1 on 2019-05-14 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5, '우선순위는 1부터 5까지만 지정할 수 있습니다.'), django.core.validators.MinValueValidator(1, '우선순위는 1부터 5까지만 지정할 수 있습니다.')])),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
    ]
